# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mlp-monitor',
                'doc_host': 'https://paulduf.github.io',
                'git_url': 'https://github.com/paulduf/mlp-monitor',
                'lib_path': 'mlp_monitor'},
  'syms': { 'mlp_monitor.core': { 'mlp_monitor.core.LossMonitor': ('core.html#lossmonitor', 'mlp_monitor/core.py'),
                                  'mlp_monitor.core.LossMonitor.__call__': ('core.html#lossmonitor.__call__', 'mlp_monitor/core.py'),
                                  'mlp_monitor.core.LossMonitor.__init__': ('core.html#lossmonitor.__init__', 'mlp_monitor/core.py'),
                                  'mlp_monitor.core.LossMonitor.losses': ('core.html#lossmonitor.losses', 'mlp_monitor/core.py'),
                                  'mlp_monitor.core.LossMonitor.plot': ('core.html#lossmonitor.plot', 'mlp_monitor/core.py'),
                                  'mlp_monitor.core.MLP': ('core.html#mlp', 'mlp_monitor/core.py'),
                                  'mlp_monitor.core.MLP.__init__': ('core.html#mlp.__init__', 'mlp_monitor/core.py'),
                                  'mlp_monitor.core.MLP.forward': ('core.html#mlp.forward', 'mlp_monitor/core.py'),
                                  'mlp_monitor.core.loss_l1': ('core.html#loss_l1', 'mlp_monitor/core.py')},
            'mlp_monitor.utils': {'mlp_monitor.utils.lookahead': ('utils.html#lookahead', 'mlp_monitor/utils.py')}}}
